### PR TITLE
Add Carbonized Celostrials to mainnet nft list

### PR DESCRIPTION
**Pull request by Bridgerz**

### CODE REVIEW

**Comment by MuckT** [comment]
@Bridgerz nit: there's an extra space on line 66.

**Comment by Bridgerz** [comment]
my bad! pushed changes

**Review by MuckT — APPROVED** [review]
LGTM and I was able to carbonize my Celostrial! 👽

**Comment by MuckT** [comment]
@Bridgerz it looks like there might be a bug in the smart contract. When I attempt to use the `tokenURI` method from the contract I am receiving an empty string: [Explorer Link](https://explorer.celo.org/mainnet/address/0xB346E32c9c5196A580F7466a039D902b505Ae7d4/read-proxy#address-tabs).

**Comment by Bridgerz** [comment]
@MuckT Thanks for the heads up! luckily its an upgradeable contract! will investigate and deploy an upgrade ASAP

**Comment by Bridgerz** [comment]
@MuckT Just deployed an upgrade that enables the `tokenURI` method. I'm still not able to see the Carbonized Collection in the nft view tho. Let me know if you find anything I need to do on my end.

**Comment by Bridgerz** [comment]
@MuckT Here's some more context. Looking at the network calls, it looks like the "getNfts" endpoint is still returning an empty "tokenUri". Does that api need to re-index or something? 
Screen Shot 2023-01-27 at 8 56 49 AM

**Comment by MuckT** [comment]
@Bridgerz I am seeing the correct response from the Explorer. I believe you are correct in that we need to have our NFT indexer re-index this contract. Looking into a fix now.

**Comment by MuckT** [comment]
@Bridgerz the Carbonized Celostrials should be viewable in the Valora NFT viewer now after a re-index.

**Comment by Bridgerz** [comment]
@MuckT All working on my side too! Thanks for your help 🚀

**Pull request merged**
